/**
 * HTML Parser Utility for Marp CLI Output
 *
 * Parses the full HTML document generated by Marp CLI and extracts:
 * - Slide content (all <section> elements)
 * - Embedded styles (all <style> tags)
 * - SVG definitions (for backgrounds and custom graphics)
 *
 * This enables injecting Marp presentations into Astro layouts.
 */

export interface ParsedMarpHtml {
  /** The slide content only (all <section> elements wrapped in a container) */
  slidesHtml: string;
  /** All embedded styles from <style> tags */
  styles: string;
  /** SVG definitions extracted from the document */
  svgDefs: string;
  /** The complete original HTML (for backward compatibility) */
  fullHtml: string;
}

/**
 * Parses Marp CLI HTML output and extracts slides, styles, and SVG definitions.
 *
 * @param html - Full HTML document from Marp CLI
 * @returns Parsed components that can be used separately in Astro layouts
 */
export function parseMarpHtml(html: string): ParsedMarpHtml {
  // Extract all <style> tags and their content
  const styles = extractStyles(html);

  // Extract SVG definitions (used for backgrounds, custom graphics, etc.)
  const svgDefs = extractSvgDefs(html);

  // Extract slide content (all <section> elements)
  const slidesHtml = extractSlides(html);

  return {
    slidesHtml,
    styles,
    svgDefs,
    fullHtml: html
  };
}

/**
 * Extracts all <style> tags and combines their content.
 */
function extractStyles(html: string): string {
  const styleRegex = /<style[^>]*>([\s\S]*?)<\/style>/gi;
  const styles: string[] = [];

  let match;
  while ((match = styleRegex.exec(html)) !== null) {
    styles.push(match[1].trim());
  }

  return styles.join('\n\n');
}

/**
 * Extracts SVG definitions from the document.
 * Marp often includes SVG defs for backgrounds and custom graphics.
 */
function extractSvgDefs(html: string): string {
  // Look for <svg style="display:none"> which contains definitions
  const svgDefsRegex = /<svg[^>]*style="display:\s*none[^"]*"[^>]*>([\s\S]*?)<\/svg>/gi;
  const defs: string[] = [];

  let match;
  while ((match = svgDefsRegex.exec(html)) !== null) {
    defs.push(match[0]); // Keep the full <svg> tag
  }

  return defs.join('\n');
}

/**
 * Extracts all slide sections from the HTML body.
 * Marp generates each slide as a <section> element.
 */
function extractSlides(html: string): string {
  // First, try to extract just the body content
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  const bodyContent = bodyMatch ? bodyMatch[1] : html;

  // Extract all <section> elements (each represents a slide)
  const sectionRegex = /<section[^>]*>[\s\S]*?<\/section>/gi;
  const sections: string[] = [];

  let match;
  while ((match = sectionRegex.exec(bodyContent)) !== null) {
    sections.push(match[0]);
  }

  if (sections.length === 0) {
    // Fallback: if no sections found, return the body content
    return bodyContent;
  }

  // Wrap sections in a container div with Marp's expected structure
  // The 'marpit' class is used by Marp's JavaScript for navigation
  return `<div id="marp" class="marpit">\n${sections.join('\n')}\n</div>`;
}

/**
 * Generates a complete HTML head section with Marp styles and SVG defs.
 * Useful for creating standalone presentations or custom layouts.
 *
 * @param parsed - Parsed Marp HTML components
 * @param title - Optional page title (defaults to "Marp Presentation")
 * @returns HTML head content as a string
 */
export function generateMarpHead(parsed: ParsedMarpHtml, title: string = "Marp Presentation"): string {
  return `<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
${parsed.styles}
    </style>
</head>`;
}

/**
 * Generates the complete body content including SVG defs and slides.
 *
 * @param parsed - Parsed Marp HTML components
 * @returns HTML body content as a string
 */
export function generateMarpBody(parsed: ParsedMarpHtml): string {
  return `${parsed.svgDefs}\n${parsed.slidesHtml}`;
}
